name: Monitor IBFC Online
on:
  schedule:
    - cron: '*/30 * * * *' # Roda a cada 30 minutos
  workflow_dispatch: # Permite que você rode manualmente para testar

jobs:
  verificacao:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar codigo do Github
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar ferramentas
        run: pip install requests beautifulsoup4

      - name: Executar o Robô
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python monitor.py

      - name: Salvar mudancas no site
        run: |
          git config --global user.name 'Robo Monitor'
          git config --global user.email 'actions@github.com'
          git add ultimo_estado.txt
          git commit -m "Site atualizado" || exit 0
          git push
